(node:2236) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSO
N input
    at JSON.parse (<anonymous>)
    at Client.bot.on (C:\Users\Dawid\Desktop\Bot  DS\index.js:42:23)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Dawid\Desktop\Bot  DS\node_modules\
discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules\ws\lib\e
vent-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\ws\lib\websocket.js:137:47)
(node:2236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:2236) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
(node:2236) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSO
N input
    at JSON.parse (<anonymous>)
    at Client.bot.on (C:\Users\Dawid\Desktop\Bot  DS\index.js:42:23)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Dawid\Desktop\Bot  DS\node_modules\
discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules\ws\lib\e
vent-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\ws\lib\websocket.js:137:47)
(node:2236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:2236) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSO
N input
    at JSON.parse (<anonymous>)
    at Client.bot.on (C:\Users\Dawid\Desktop\Bot  DS\index.js:42:23)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Dawid\Desktop\Bot  DS\node_modules\
discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_module
s\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules\ws\lib\e
vent-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (C:\Users\Dawid\Desktop\Bot  DS\node_modules
\ws\lib\websocket.js:137:47)
(node:2236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 3)