<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>2d2514ea8623b0bd5b3e69a8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2018-07-05 17:31:27</createtime><buildsignature>Local.Unknown.Unknown.1.44.83.1020-1.200.000.350.Release</buildsignature><categoryid>object_creation.py:124</categoryid><desyncid>2d2514ea8623b0bd5b3e69a8</desyncid><systemconfig/><screenshot/><desyncdata>Exception when applying action &lt;ObjectCreationOp ParticipantType.Actor&gt; for loot &lt;class 'sims4.tuning.instances.KawaiiStacie:loot_Object_Icecream'&gt; (AttributeError: 'NoneType' object has no attribute 'final_product')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 205, in c_api_server_tick&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\events\core_tick.py", line 102, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 464, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 140, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 88, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 373, in apply_to_resolver&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\special\exception_watcher.py", line 16, in _turbolib_on_exception_log&#13;&#10;  File ".\mc_utils.py", line 115, in _wrapper_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 371, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 211, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 702, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 487, in initialize_helper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 497, in definition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 124, in get_definition&#13;&#10;AttributeError: 'NoneType' object has no attribute 'final_product'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>2d2514ea8623b0bd5b3e69a8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2018-07-05 17:31:27</createtime><buildsignature>Local.Unknown.Unknown.1.44.83.1020-1.200.000.350.Release</buildsignature><categoryid>object_creation.py:124</categoryid><desyncid>2d2514ea8623b0bd5b3e69a8</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'final_product')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 140, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 88, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 374, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 371, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 211, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 702, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 487, in initialize_helper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 497, in definition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 124, in get_definition&#13;&#10;AttributeError: 'NoneType' object has no attribute 'final_product'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>2d2514ea8623b0bd5b3e69a8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2018-07-05 17:31:43</createtime><buildsignature>Local.Unknown.Unknown.1.44.83.1020-1.200.000.350.Release</buildsignature><categoryid>object_creation.py:124</categoryid><desyncid>2d2514ea8623b0bd5b3e69a8</desyncid><systemconfig/><screenshot/><desyncdata>Exception when applying action &lt;ObjectCreationOp ParticipantType.Actor&gt; for loot &lt;class 'sims4.tuning.instances.KawaiiStacie:loot_Object_Icecream'&gt; (AttributeError: 'NoneType' object has no attribute 'final_product')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 205, in c_api_server_tick&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\events\core_tick.py", line 102, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 464, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 140, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 88, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 373, in apply_to_resolver&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File ".\WickedWhims 3.3.4.129g\turbolib\special\exception_watcher.py", line 16, in _turbolib_on_exception_log&#13;&#10;  File ".\mc_utils.py", line 115, in _wrapper_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 371, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 211, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 702, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 487, in initialize_helper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 497, in definition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 124, in get_definition&#13;&#10;AttributeError: 'NoneType' object has no attribute 'final_product'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>2d2514ea8623b0bd5b3e69a8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2018-07-05 17:31:43</createtime><buildsignature>Local.Unknown.Unknown.1.44.83.1020-1.200.000.350.Release</buildsignature><categoryid>object_creation.py:124</categoryid><desyncid>2d2514ea8623b0bd5b3e69a8</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'final_product')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 140, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 88, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 374, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 371, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 211, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 702, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 487, in initialize_helper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 497, in definition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_creation.py", line 124, in get_definition&#13;&#10;AttributeError: 'NoneType' object has no attribute 'final_product'&#13;&#10;</desyncdata></report>
</root>