Traceback (most recent call last):
  File "/home/mikado/mydevenv/pyrenv/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.4.2', 'console_scripts', 'paster')()
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/serve.py", line 321, in loadapp
    **kw)
  File "/usr/lib/pymodules/python2.6/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/pymodules/python2.6/paste/deploy/loadwsgi.py", line 225, in loadobj
    return context.create()
  File "/usr/lib/pymodules/python2.6/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/usr/lib/pymodules/python2.6/paste/deploy/loadwsgi.py", line 110, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/pymodules/python2.6/paste/deploy/util/fixtypeerror.py", line 57, in fix_call
    val = callable(*args, **kw)
  File "/home/mikado/mydevenv/workspace/vte/assetcloud/slashDB/slashdb/__init__.py", line 12, in main
    config = Configurator(settings=settings)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/config/__init__.py", line 255, in __init__
    exceptionresponse_view=exceptionresponse_view,
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/config/__init__.py", line 368, in setup_registry
    self.include(inc)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/config/__init__.py", line 616, in include
    c(configurator)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid_debugtoolbar-0.9.4-py2.6.egg/pyramid_debugtoolbar/__init__.py", line 51, in includeme
    config.include('pyramid_jinja2')
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/config/__init__.py", line 600, in include
    c = self.maybe_dotted(callable)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/config/__init__.py", line 702, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/util.py", line 144, in maybe_resolve
    return self._zope_dottedname_style(dotted)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid-1.2.1-py2.6.egg/pyramid/util.py", line 123, in _zope_dottedname_style
    found = __import__(used)
  File "/home/mikado/mydevenv/pyrenv/lib/python2.6/site-packages/pyramid_jinja2-1.2-py2.6.egg/pyramid_jinja2/__init__.py", line 290, in <module>
    implementer(ITemplateRenderer)(Jinja2TemplateRenderer) # 2.5 compat, ugh
  File "/usr/lib/python2.6/dist-packages/zope/interface/declarations.py", line 496, in __call__
    raise TypeError("Can't use implementer with classes.  Use one of "
TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.